### ISSUE TITLE
PureFlow no longer available on the App Store

### ISSUE THREAD

**Issue by poislagarde** [akozlov/FlowCharts#1]
Hi @akozlov sorry if this isn’t the best place for this, but I wanted to know if PureFlow is coming back to the App Store?

I loved it on my old iPad, but I can’t download it again now that it’s gone from the App Store.

Thank you

**Comment by akozlov** [comment]
Hi @poislagarde! The app is no longer available because it does not work on iOS 13. Actually, right now I'm working on a new version, but I can't promise anything.

**Comment by poislagarde** [comment]
@akozlov that's great news. I'll look forward to it.
Thank you for your answer.
